mysite/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^home/', include('polls.urls')),
]

polls/urls.py
from django.conf.urls import url
from . import views

app_name = 'polls'

urlpatterns = [
    # /home/
    url(r'^$', views.IndexView.as_view(), name='index'),

    #/home/<album_id>
    url(r'^(?P<pk>[0-9]+)/$',views.DetailView.as_view(),name='detail'),
    #/home/album/add/
    url(r'album/add/$',views.AlbumCreate.as_view(),name='album-add'),

    #/home/album/2/
    url(r'album/(?P<pk>[0-9]+)/$',views.AlbumUpdate.as_view(),name='album-update'),

    #/home/album/add/
    url(r'album/(?P<pk>[0-9]+)/delete/$',views.AlbumDelete.as_view(),name='album-delete'),


]

polls/models.py
from django.db import models
from django.core.urlresolvers import reverse

class Album(models.Model):
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=500)
    genre = models.CharField(max_length=100)
    album_logo = models.CharField(max_length=1000)


    def get_absolute_url(self):
        return reverse('polls:detail',kwargs={'id': self.id})

    def __str__(self):
        return self.album_title + " " + self.artist

class Song(models.Model):
    album = models.ForeignKey(Album,on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=250)
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.song_title

polls/views.py
from django.views import generic
from .models import Album,Song
from django.views.generic.edit import CreateView,UpdateView,DeleteView
from django.core.urlresolvers import reverse_lazy

class IndexView(generic.ListView):
    template_name = 'polls/index.html'

    def get_queryset(self):
        return Album.objects.all()


class DetailView(generic.DetailView):
    model = Album
    template_name = 'polls/details.html'


class AlbumCreate(CreateView):
    model = Album
    fields = ['artist','album_title','genre','album_logo']

class AlbumUpdate(UpdateView):
    model = Album
    fields = ['artist','album_title','genre','album_logo']

class AlbumDelete(DeleteView):
    model = Album
    success_url = reverse_lazy('polls:index')

polls/templates/polls/album_form.html
{% extends 'polls/header.html' %}

{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">

                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'polls/form-template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

polls/templates/polls/details.html
{% extends 'polls/header.html' %}

{% block body %}
    <img src="{{album.album_logo}}">
    <h1>{{ album.album_title }}</h1>
    <h2>{{ album.artist }}</h2>
<ul>
{% for song in album.song_set.all %}
<li>{{song.song_title}}</li>
{%endfor%}
</ul>
<form action="{% url 'polls:album-delete' album.id %}" method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-default btn-sm">
        <span class="glyphicon glyphicon-trash"></span>
    </button>
</form>

    {% if error_message %}
        <p><strong>{{ error_message }}</strong></p>
    {% endif %}


    <style>
    img{
     height: 150px;
    width: 150px;
    }
</style>
{% endblock  %}

polls/templates/polls/form-template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.error }}</span>
        </div>
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{%endfor%}

polls/templates/polls/header.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
	{% load staticfiles %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}"/>
<link href="https://fonts.googleapis.com/css?family=Satisfy" rel="stylesheet">
<script src="https://code.jquery.com/jquery-3.2.1.slim.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
	<div class="container-fluid">
		<!-- header-->
		<div class="navbar-header">
			<button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#topNavBar">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="{% url 'polls:index' %}">Home</a>
		</div>

		<!-- items-->
		<div class="collapse navbar-collapse" id="top-navbar">
			
			<ul class="nav navbar-nav">
				<li class="">
					<a href="{% url 'polls:index' %}">
						<span class="glyphicon glyphicon-cd" aria_hidden="true"></span>&nbsp;
						Albums
					</a>
				</li>
				<li class="">
					<a href="{% url 'polls:index' %}">
						<span class="glyphicon glyphicon-music" aria_hidden="true"></span>&nbsp;
						Song
					</a>
				</li>
			</ul>

			<form class="navbar-form navbar-left" role="search" method="get" action="#">
				<div class="form-group">
					<input type="text" class="form-control" name="q" value="">
				</div>
				<button type="submit" class="btn btn-default">Search</button>
			</form>

			<ul class="nav navbar-nav navbar-right">
				<li class="">
					<a href="{% url 'polls:album-add' %}">
						<span class="glyphicon glyphicon-plus" aria_hidden="true"></span>&nbsp;
						Add Album
					</a>
				</li>
				<li class="">
					<a href="{% url 'polls:index' %}">
						<span class="glyphicon glyphicon-off" aria_hidden="true"></span>&nbsp;
						Logout
					</a>
				</li>
			</ul>
		</div>
	</div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

polls/templates/polls/index.html
{% extends 'polls/header.html'%}


{% block body %}
	{% if object_list %}
	    <h3>Here are all my Albums:</h3>
	    <ul>
	        {% for album in object_list %}
	        <li><a href="{% url 'polls:detail' album.id %}">{{ album.album_title }}</a></li>
	        {% endfor %}
	    </ul>
	{% else %}
	    <h3>You don't have any albums</h3>
	{% endif %}
{% endblock  %}